feat: configure runtime hooks in sdk
succinctlabs/sp1 pull request #931
Opened 2024-06-14 01:19 UTC by tqn

the method duplication is kind of janky unfortunately

2024-06-14 03:32 UTC, ctian1 requested changes

2024-06-14 03:32 UTC, ctian1 commented on sdk/src/provers/mock.rs
> +    /// TODO find out what to actually impl here
don't need this comment?

2024-06-14 22:17 UTC, tqn commented
Building off of this PR in #940, where we refactor a lot of stuff.

2024-06-18 17:07 UTC, tqn commented
Changes merged in #940.

2024-06-18 17:07 UTC, closed without merging